version: '3'
services:
  app:
    build: .
    pull_policy: build
    container_name: kirby-cafe-reserve
    ports:
      - 3002:3002
    environment:
      - PORT=3002
    volumes:
      - ./data:/home/pptruser/screenshots # Montaje de volúmenes para persistir datos si es necesario
    restart: unless-stopped
